spring:
  application:
    name: iot
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/iot_manager?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 34567
  tomcat:
    threads:
      max: 100
  servlet:
    session:
      timeout: 600 #设置会话超时时间,单位是秒


# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: top.nomelin.iot.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  file:
    path: /logs


system:
  env: dev

iotdb:
  ip: 127.0.0.1
  port: 6667
  username: root
  password: root
  storage:
    ts-encoding: PLAIN
    compression-type: LZ4
    compatible:
      batch-query: true
  #      dont-merge: true
  startPath: D:\lib\毕业设计\iotdb\apache-iotdb-1.3.3-all-bin\sbin\start-standalone.bat
  stopPath: D:\lib\毕业设计\iotdb\apache-iotdb-1.3.3-all-bin\sbin\stop-standalone.bat
  query:
    timeout: 60000 # iotdb查询超时时间，单位毫秒
    try-fast-aggregate: true # 是否尝试使用快速聚合查询，建议保持开启。失败会自动降级到传统查询。
    fast-aggregate-error-send-message: true # 是否快速聚合查询失败时发送消息
    aggregate-query-limit-size: 3000000 # 如果不使用快速聚合查询时，聚合查询限制的数据点数量，避免系统压力过大。
  retry:
    max: 3 # 最大重试次数
    initial-interval: 100 # 单位毫秒，首次重试间隔
    multiplier: 3 # 指数退避系数 100，100*3，100*3*3...
  session:
    pool:
      max: 50
      min-idle: 5
      max-wait-seconds: 10 # 最大等待时间（获取连接时阻塞的时间）

file:
  tempDir: D:\lib\毕业设计\project\iot\temp\upload\

task:
  auto-clean:
    fail_expired_days: 1
    ongoing_expired_days: 7

debug:
  print-extra-info: false

connect:
  default-buffer-size: 1024
  default-flush-interval: 10

file-thread-pool:
  core-pool-size: 16         # 核心线程数，默认10
  max-pool-size: 32          # 最大线程数，默认20
  queue-capacity: 8192        # 队列容量，默认500
  thread-name-prefix: "FileProcessor-"

pushplus:
  daily-global-limit: 100
  user-token-bucket-size: 5
  user-token-refresh-interval: 1800
  token: 真正的pushplus token

cache:
  enabled: true
